export const textDialogBeforeFirst = [
    {picture: `hermes`, sound: `hermes1`,   text: `Bienvenue dans mon centre de distribution de colis supervisés par les Amazones en personnes.\nOn a énormément de boulot et Bezos notre stagiaire s’est fait enlever par Hadès, on a bien besoin de ton aide.`},
    {picture: `pathos`, sound: `pat6`,      text: `Je peux savoir pourquoi tu parles aussi vite et surtout pourquoi on se trouve dans le labyrinthe de Dédale ?`},
    {picture: `hermes`, sound: `hermes2`,   text: `Les Satyres nous volaient constamment notre marchandise, ici ils ne peuvent pas nous trouver,\net de toute façon ces couards craignent trop le Minotaure.`},
    {picture: `pathos`, sound: `pat7`,      text: `Huuum, je vais faire comme si c’était logique. Qu'est-ce que je suis censé faire ?`},
    {additional : `parcheminMap`, picture: `hermes`, sound: `hermes3`,   text: `Les objets à livrer vont apparaître à gauche, juste ici. Un nouveau apparaît dès que le précédent a été expédié.\nTu dois ensuite les amener à nos chers minotaures emballeuses Kobé et Milkos qui se trouvent au milieu du labyrinthe.\nCela leur prendra un peu de temps, donc n’hésite pas à vaquer à tes occupations en attendant.\nUne fois le colis emballé, elles te préviendront en beuglant.\nFinalement, il te faudra amener les colis vers la boîte aux lettres adéquates et les y poster.\nAttention, retiens bien ce que tu places dans les cartons, nos amis les vaches sont daltoniennes,\nelles ne pourront donc pas te le rappeler.`},
    {picture: `pathos`, sound: `pat8`,      text: `Oui d’accord c’est assez trivial, fin je vois pas trop comment je pourrai échouer ça. Déjà moi je suis pas un raté de daltonien.`},
    {additional : `parcheminObjets`, picture: `hermes`, sound: `hermes4`,   text: `Voici les objets que tu peux croiser, ainsi qu’à qui tu dois les livrer.\nPrend garde à ne pas faire trop d’erreur, ce sont des clients assez colériques,\non ne voudrait pas que méduse vienne encore se plaindre, elle change très vite d’humeur et en pierre.\nOn a déjà 3 statues de vaches dans les locaux.`},
    {picture: `pathos`, sound: `pat9`,      text: `De la crème solaire ? Pour Icare ? Ça te fait rire je suppose …`},
    {picture: `hermes`, sound: `hermes5`,   text: `Beaucoup. Pour que tu ailles plus vite, je te prête mes sandales qui te permettront de bondir en avant\n, attention c’est assez incontrôlable.\nAppuie sur shift pour les utiliser.`},
    {picture: `pathos`, sound: `pat10`,     text: `Shift ?`},
    {picture: `hermes`, sound: `hermes6`,   text: `prf, j’ai pas compris non plus. Pose pas trop de questions on n’a pas vraiment le temps, au boulot !`},
]